services:
  api-server:
    build:
      dockerfile: Dev.Dockerfile
      context: server
    develop:
      watch:
        - action: rebuild
          path: "server/internal"
        - action: rebuild
          path: "server/cmd"
        - action: rebuild
          path: "server/go.mod"
        - action: rebuild
          path: "server/go.sum"
    command: "go run cmd/main.go"
